{{- if (and .Values.otel.collector.enabled (le 1 (int .Values.phase))) }}
apiVersion: v1
kind: Secret
metadata:
  name: otel-grafanacloud-creds
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "observibelity.labels" . | nindent 4 }}
    app.kubernetes.io/component: otel-collector
type: Opaque
stringData:
  GRAFANA_CLOUD_OTLP_ENDPOINT: {{ .Values.otel.grafanaCloud.otlpEndpoint | quote }}
  GRAFANA_CLOUD_INSTANCE_ID: {{ .Values.otel.grafanaCloud.instanceId | quote }}
  GRAFANA_CLOUD_API_TOKEN: {{ .Values.otel.grafanaCloud.apiToken | quote }}
{{- end }}
