// ObserVIBElity web wizard — deploy.js
// Pure vanilla JS. Runs entirely in the browser. Never POSTs anywhere.

'use strict';

const REGION_TO_OTLP = {
  'us-east': 'https://otlp-gateway-prod-us-east-0.grafana.net/otlp',
  'us-central': 'https://otlp-gateway-prod-us-central-0.grafana.net/otlp',
  'eu-west': 'https://otlp-gateway-prod-eu-west-0.grafana.net/otlp',
  'ap-southeast': 'https://otlp-gateway-prod-ap-southeast-0.grafana.net/otlp',
};

function regionToOtlpEndpoint(region) {
  return REGION_TO_OTLP[region] || REGION_TO_OTLP['us-east'];
}

function $(id) {
  return document.getElementById(id);
}

function setError(fieldId, message) {
  const errEl = $('err-' + fieldId);
  const inputEl = $(fieldId);
  if (errEl) errEl.textContent = message || '';
  if (inputEl) {
    if (message) inputEl.classList.add('has-error');
    else inputEl.classList.remove('has-error');
  }
}

function clearAllErrors() {
  document.querySelectorAll('.error').forEach((e) => (e.textContent = ''));
  document.querySelectorAll('.has-error').forEach((e) => e.classList.remove('has-error'));
}

function readForm() {
  return {
    anthropicKey: $('anthropic-key').value.trim(),
    gcInstance: $('gc-instance').value.trim(),
    gcToken: $('gc-token').value.trim(),
    gcRegion: $('gc-region').value,
    githubSkip: $('github-skip').checked,
    githubToken: $('github-token').value.trim(),
    githubOrg: $('github-org').value.trim(),
    ollamaUrl: $('ollama-url').value.trim(),
    ingressHost: $('ingress-host').value.trim(),
    storageClass: $('storage-class').value.trim(),
  };
}

function validateForm() {
  clearAllErrors();
  const data = readForm();
  let ok = true;

  if (!data.anthropicKey) {
    setError('anthropic-key', 'Required. Get one at console.anthropic.com.');
    ok = false;
  }
  if (!data.gcInstance) {
    setError('gc-instance', 'Required. Find it in Grafana Cloud → Stack details.');
    ok = false;
  } else if (!/^[0-9]+$/.test(data.gcInstance)) {
    setError('gc-instance', 'Instance ID is numeric (e.g. 1234567).');
    ok = false;
  }
  if (!data.gcToken) {
    setError('gc-token', 'Required. Create one under Access Policies.');
    ok = false;
  }
  if (!data.gcRegion) {
    setError('gc-region', 'Pick a region.');
    ok = false;
  }
  if (!data.githubSkip) {
    if (!data.githubToken) {
      setError('github-token', 'Required (or check Skip GitHub fork).');
      ok = false;
    }
    if (!data.githubOrg) {
      setError('github-org', 'Required (or check Skip GitHub fork).');
      ok = false;
    }
  }
  if (!data.ingressHost) {
    setError('ingress-host', 'Required. Default: neoncart.localhost');
    ok = false;
  }
  return ok;
}

function generateEnv(data) {
  const now = new Date().toISOString();
  const otlp = regionToOtlpEndpoint(data.gcRegion);
  const lines = [
    '# Generated by ObserVIBElity web wizard on ' + now,
    '# https://stephenwagner-grafana.github.io/observibelity/wizard/',
    '',
    '# Phase + apps',
    'PHASE=0',
    'APPS=neoncart',
    '',
    '# Anthropic',
    'ANTHROPIC_API_KEY=' + data.anthropicKey,
    '',
    '# Grafana Cloud',
    'GRAFANA_CLOUD_INSTANCE_ID=' + data.gcInstance,
    'GRAFANA_CLOUD_API_TOKEN=' + data.gcToken,
    'GRAFANA_CLOUD_REGION=' + data.gcRegion,
    'GRAFANA_CLOUD_OTLP_ENDPOINT=' + otlp,
    '',
    '# GitHub',
  ];
  if (data.githubSkip) {
    lines.push('# Skipped via --no-fork');
    lines.push('OBSERVIBELITY_NO_FORK=1');
    lines.push('GITHUB_TOKEN=');
    lines.push('GITHUB_ORG=');
  } else {
    lines.push('GITHUB_TOKEN=' + data.githubToken);
    lines.push('GITHUB_ORG=' + data.githubOrg);
  }
  lines.push('');
  lines.push('# Optional: Ollama');
  lines.push('OLLAMA_BASE_URL=' + data.ollamaUrl);
  lines.push('');
  lines.push('# Cluster');
  lines.push('INGRESS_HOST_NEONCART=' + data.ingressHost);
  lines.push('STORAGE_CLASS=' + data.storageClass);
  lines.push('');
  return lines.join('\n');
}

function copyToClipboard(text) {
  const btn = $('copy-btn');
  const original = btn.textContent;
  const flash = (msg) => {
    btn.textContent = msg;
    setTimeout(() => (btn.textContent = original), 1500);
  };
  if (navigator.clipboard && navigator.clipboard.writeText) {
    navigator.clipboard
      .writeText(text)
      .then(() => flash('Copied!'))
      .catch(() => flash('Copy failed'));
  } else {
    // Fallback for older browsers
    const ta = document.createElement('textarea');
    ta.value = text;
    ta.setAttribute('readonly', '');
    ta.style.position = 'absolute';
    ta.style.left = '-9999px';
    document.body.appendChild(ta);
    ta.select();
    try {
      document.execCommand('copy');
      flash('Copied!');
    } catch (e) {
      flash('Copy failed');
    }
    document.body.removeChild(ta);
  }
}

function downloadEnv(content) {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = '.env';
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

function toggleSecretVisibility(id) {
  const el = $(id);
  if (!el) return;
  const btn = document.querySelector('button[data-toggle="' + id + '"]');
  if (el.type === 'password') {
    el.type = 'text';
    if (btn) btn.textContent = 'Hide';
  } else {
    el.type = 'password';
    if (btn) btn.textContent = 'Show';
  }
}

function updateGithubVisibility() {
  const skip = $('github-skip').checked;
  const fields = $('github-fields');
  if (!fields) return;
  if (skip) {
    fields.classList.add('hidden');
    clearAllErrors();
  } else {
    fields.classList.remove('hidden');
  }
}

document.addEventListener('DOMContentLoaded', function () {
  // Show/hide toggle buttons
  document.querySelectorAll('button[data-toggle]').forEach((btn) => {
    btn.addEventListener('click', () => toggleSecretVisibility(btn.dataset.toggle));
  });

  // Skip-fork toggle
  const skip = $('github-skip');
  if (skip) {
    skip.addEventListener('change', updateGithubVisibility);
    updateGithubVisibility();
  }

  // Form submit
  const form = $('deploy-form');
  if (form) {
    form.addEventListener('submit', (e) => {
      e.preventDefault();
      if (!validateForm()) return;
      const data = readForm();
      const env = generateEnv(data);
      $('env-out').textContent = env;
      const out = $('output');
      out.classList.remove('hidden');
      out.scrollIntoView({ behavior: 'smooth', block: 'start' });
    });
  }

  // Copy + Download
  const copyBtn = $('copy-btn');
  if (copyBtn) copyBtn.addEventListener('click', () => copyToClipboard($('env-out').textContent));
  const dlBtn = $('download-btn');
  if (dlBtn) dlBtn.addEventListener('click', () => downloadEnv($('env-out').textContent));
});
