{{- if (and .Values.postgres.enabled (le 1 (int .Values.phase))) }}
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "observibelity.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    {{- include "observibelity.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
{{- end }}
