{{- if (and .Values.postgres.enabled (le 1 (int .Values.phase))) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: observibelity-migrate
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "observibelity.labels" . | nindent 4 }}
    app.kubernetes.io/component: migrate
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      labels:
        {{- include "observibelity.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: migrate
    spec:
      restartPolicy: OnFailure
      {{- with .Values.podDefaults.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: migrate
          image: "{{ .Values.global.imageRegistry }}/observibelity-migrate:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          command: ["alembic"]
          args: ["upgrade", "head"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-creds
                  key: DATABASE_URL
            - name: OTEL_SERVICE_NAME
              value: observibelity-migrate
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector:4318
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: http/protobuf
          {{- if .Values.podDefaults.enabled }}
          resources:
            {{- toYaml .Values.podDefaults.resources | nindent 12 }}
          {{- end }}
{{- end }}
