"""request_access — file a ticket requesting access to a resource.

Side-effect, idempotent (filing the same access request twice in quick
succession is harmless — the duplicate is closed by the IT team). Reuses
the tickets table.

Schema sync (migrations/versions/0006_tickets.py):
  * ``tickets`` has no ``category`` column; the request kind ("access-
    request") lives in the subject. ``ticket_number`` is NOT NULL — must
    be generated by the tool. persona_id is a string slug FK. Older
    drafts violated all three constraints.
"""
from __future__ import annotations

import uuid
from datetime import datetime, timezone
from typing import Optional

from pydantic import BaseModel, Field
from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession

from tool_base import Tool


class RequestAccessArgs(BaseModel):
    persona_id: str = Field(..., min_length=1, max_length=64)
    resource: str = Field(..., min_length=1, max_length=255)
    justification: Optional[str] = Field(None, max_length=2048)


class RequestAccessResult(BaseModel):
    ticket_id: int
    ticket_number: str
    resource: str
    status: str
    created_at: datetime


class RequestAccess(Tool):
    NAME = "request_access"
    SIDE_EFFECT = True
    IDEMPOTENT = True
    TIMEOUT_SEC = 5
    MAX_CONCURRENCY = 20
    CACHE_TTL_SEC = 0
    RETRIES = 1
    BACKING_TABLES = ["tickets"]
    ALLOWED_CALLERS = ["sb-it-troubleshoot", "sb-escalator"]
    REPLICAS = 1

    Args = RequestAccessArgs
    Result = RequestAccessResult

    async def execute(
        self,
        args: RequestAccessArgs,
        session: AsyncSession | None = None,
    ) -> RequestAccessResult:
        assert session is not None, "request_access requires a DB session"
        now = datetime.now(tz=timezone.utc)
        ticket_number = f"T-{uuid.uuid4().hex[:10]}"
        body = (
            f"Resource requested: {args.resource}\n"
            f"Justification: {args.justification or '(none provided)'}"
        )
        stmt = text(
            """
            INSERT INTO tickets
                   (ticket_number, persona_id, subject, body, status, priority, created_at)
            VALUES (:tnum, :pid, :subj, :body, 'open', 'medium', :ts)
            RETURNING id, ticket_number, status, created_at
            """
        )
        row = (
            await session.execute(
                stmt,
                {
                    "tnum": ticket_number,
                    # persona_id is a string slug; pass through verbatim.
                    "pid": args.persona_id,
                    "subj": f"Access request: {args.resource}",
                    "body": body,
                    "ts": now,
                },
            )
        ).one()
        await session.commit()
        return RequestAccessResult(
            ticket_id=int(row.id),
            ticket_number=row.ticket_number,
            resource=args.resource,
            status=row.status,
            created_at=row.created_at,
        )
